In [45]:
import numpy as np
import pandas as pm 
import matplotlib.pyplot as plt
import seaborn as sb
sb.set()

from sklearn.linear_model import LinearRegression 

In [46]:
data = pm.read_csv("Multiple_linear_regression.csv")

In [47]:
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [48]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [49]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [50]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [51]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [52]:
reg.intercept_

0.29603261264909486

In [53]:
x.shape

(84, 2)

In [54]:
x.shape

(84, 2)

In [55]:
reg.score(x,y)

0.4066811952814282

$R^2_{adj.} = 1 - (1- R^2)*\frac{n-1}{n-p-1}$  

In [56]:
r2 = reg.score(x,y)

n = x.shape[0]
p = x.shape[1]

adj_r2 = 1 - (1- r2)*(n-1)/(n-p-1)
adj_r2

0.39203134825134

In [57]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

IN above array 1st one is F-stats and 2nd is P-values

In [58]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [59]:
p_values.round(3)

array([0.   , 0.676])

In [60]:
reg_summary = pm.DataFrame(x.columns.values, columns= ['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [61]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values']  = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [62]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [63]:
scaler.fit(x)

StandardScaler()

In [64]:
x_scaled = scaler.transform(x)

In [65]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [66]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [67]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [68]:
reg.intercept_

3.330238095238095

In [69]:
reg_summary = pm.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']],columns=['Features'])
reg_summary['Weights'] =  reg.intercept_,reg.coef_[0],reg.coef_[1]

In [70]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [71]:
new_data = pm.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [72]:
reg.predict(new_data)

c:\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [73]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [74]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [79]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [80]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])